## Table of Contents:
* [Categorical Naive Bayes](#categorical_naive_bayes)
* [Data load](#data_load_catg)
* [Math Explanation](#math_expl_catg)
* [SciKit CategoricalNB](#sci_cnb)
* [Questions](#questions)

In [1]:
import pandas as pd
import traceback
import numpy as np
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,LabelBinarizer
from sklearn.naive_bayes import CategoricalNB

## Categorical Naive Bayes <a class="anchor" id="categorical_naive_bayes"></a>
$
\begin{align}
& \hat{y} = \underset{k \in {1, .., K}}{\mathrm{arg\,max}} P(y_k) \prod_{i=1}^{d} p(x_i | y_k) \\
& P(x_{i}\mid y_{k}) = \frac{(N_{tic} + \alpha)}{(N_{c} + \alpha n_{i})}
\end{align}
$
<br><br>
where $N_{tic}$ is the number of times category $t$ appears in feature $x_{i}$ when $y=k$, <b>[COUNT]</b> and <br>
$N_{c}$ it the number of times $y=k$. <br>
$\alpha$ is a hyperparameter introduced to reduce overfitting on the train set and <br>
$n_{i}$ is the number of catergories in the feature $x_{i}$.<br>

## Data load <a class="anchor" id="data_load_catg"></a>
https://www.kaggle.com/code/gautigadu091/categorical-naive-bayes-from-scratch-in-python/notebook <br>
-- selected three features ['weather', 'timeOfWeek', 'timeOfDay'] <br>
-- target is 'trafficJam' ~ Yes or No <br>

In [2]:
def get_conf():
    try:
        conf = {
            "data_fl_path": "../DataSets/weather.csv"
        }
        
        return conf
    except Exception as e:
        raise e

In [3]:
def load_data(conf):
    try:
        df = pd.read_csv(conf["data_fl_path"])
        return df
    except Exception as e:
        raise e

In [4]:
def populateFreq(df):
    try:
        weather_crosstab = pd.crosstab(index=df["weather"], 
                            columns=df["trafficJam"],
                            margins=True, margins_name="Total")   # Include row and column totals
        display(weather_crosstab)
        
        timeOfWeek_crosstab = pd.crosstab(index=df["timeOfWeek"], 
                            columns=df["trafficJam"],
                            margins=True, margins_name="Total")   # Include row and column totals
        display(timeOfWeek_crosstab)
        
        timeOfDay_crosstab = pd.crosstab(index=df["timeOfDay"], 
                            columns=df["trafficJam"],
                            margins=True, margins_name="Total")   # Include row and column totals
        display(timeOfDay_crosstab)
        
    except Exception as e:
        raise e

In [5]:
def data_explor():
    try:
        conf = get_conf()
        df = load_data(conf)
        display("Number of  Classes in dataset")
        display(df['trafficJam'].value_counts())
        display(df.head())
        populateFreq(df)
        return df
    except Exception as e:
        traceback.print_exc()
        
data_df = data_explor()

'Number of  Classes in dataset'

Yes    10
No      8
Name: trafficJam, dtype: int64

  weather timeOfWeek timeOfDay trafficJam
0   Clear    Workday   Morning        Yes
1   Clear    Workday     Lunch         No
2   Clear    Workday   Evening        Yes
3   Clear    Weekend   Morning         No
4   Clear    Weekend     Lunch         No

trafficJam  No  Yes  Total
weather
Clear        4    2      6
Rainy        3    3      6
Snowy        1    5      6
Total        8   10     18

trafficJam  No  Yes  Total
timeOfWeek
Weekend      7    2      9
Workday      1    8      9
Total        8   10     18

trafficJam  No  Yes  Total
timeOfDay
Evening      2    4      6
Lunch        4    2      6
Morning      2    4      6
Total        8   10     18

## Math Explanation <a class="anchor" id="math_expl_catg"></a>

<table style="float:left">
    <tr>
         <td>
            <table>
                <tr>
                    <td colspan=3> Frequency Table </td>
                </tr>
                <tr>
                    <td> Class </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td> 8 </td>
                    <td> 10 </td>
                    <td> 18 </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> Class </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td> 8/18 </td>
                    <td> 10/18 </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> Class </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td> 0.44444 </td>
                    <td> 0.55555 </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Log Likelihood Table </td>
                </tr>
                <tr>
                    <td> Class </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td> -0.81094021 </td>
                    <td> -0.587796665 </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
    </tr>    
</table>

<table style="float:left">
    <tr>
         <td>
            <table>
                <tr>
                    <td colspan=3> Frequency Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> weather </td>
                    <td> Clear </td>
                    <td> 4 </td>
                    <td> 2 </td>
                    <td> 6 </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Rainy </td>
                    <td> 3 </td>
                    <td> 3 </td>
                    <td> 6 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Snowy </td>
                    <td> 1 </td>
                    <td> 5 </td>
                    <td> 6 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> 8 </td>
                    <td> 10 </td>
                    <td> 18 </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> weather </td>
                    <td> Clear </td>
                    <td> 4/8 </td>
                    <td> 2/10 </td>
                    <td> 6/18 </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Rainy </td>
                    <td> 3/8 </td>
                    <td> 3/10 </td>
                    <td> 6/18 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Snowy </td>
                    <td> 1/8 </td>
                    <td> 5/10 </td>
                    <td> 6/18 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> 8/18 </td>
                    <td> 10/18 </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> weather </td>
                    <td> Clear </td>
                    <td> 0.5 </td>
                    <td> 0.2 </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Rainy </td>
                    <td> 0.375 </td>
                    <td> 0.3 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Snowy </td>
                    <td> 0.125 </td>
                    <td> 0.5 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Log Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> weather </td>
                    <td> Clear </td>
                    <td> -0.693147181 </td>
                    <td> -1.609437913 </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Rainy </td>
                    <td> -0.980829253 </td>
                    <td> -1.203972804 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Snowy </td>
                    <td> -2.079441541 </td>
                    <td> -0.69314718 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                </tr>
            </table>
        </td>
    </tr>    
</table>

<table style="float:left">
    <tr>
         <td>
            <table>
                <tr>
                    <td colspan=3> Frequency Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfWeek </td>
                    <td> Weekend </td>
                    <td> 7 </td>
                    <td> 2 </td>
                    <td> 9 </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Workday </td>
                    <td> 1 </td>
                    <td> 8 </td>
                    <td> 9 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> 8 </td>
                    <td> 10 </td>
                    <td> 18 </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfWeek </td>
                    <td> Weekend </td>
                    <td> 7/8 </td>
                    <td> 2/10 </td>
                    <td> 9/18 </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Workday </td>
                    <td> 1/8 </td>
                    <td> 8/10 </td>
                    <td> 9/18 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> 8/18 </td>
                    <td> 10/18 </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfWeek </td>
                    <td> Weekend </td>
                    <td> 0.875 </td>
                    <td> 0.2 </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Workday </td>
                    <td> 0.125 </td>
                    <td> 0.8 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> </td>
                    <td> </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfWeek </td>
                    <td> Weekend </td>
                    <td> -0.133531392 </td>
                    <td> -1.609437913 </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Workday </td>
                    <td> -2.0794415416 </td>
                    <td> -0.223143551 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> </td>
                    <td> </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
    </tr>    
</table>

<table style="float:left">
    <tr>
         <td>
            <table>
                <tr>
                    <td colspan=3> Frequency Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfDay </td>
                    <td> Evening </td>
                    <td> 2 </td>
                    <td> 4 </td>
                    <td> 6 </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Lunch </td>
                    <td> 4 </td>
                    <td> 2 </td>
                    <td> 6 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Morning </td>
                    <td> 2 </td>
                    <td> 4 </td>
                    <td> 6 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> 8 </td>
                    <td> 10 </td>
                    <td> 18 </td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfDay </td>
                    <td> Evening </td>
                    <td> 2/8 </td>
                    <td> 4/10 </td>
                    <td> 6/18 </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Lunch </td>
                    <td> 4/8 </td>
                    <td> 2/10 </td>
                    <td> 6/18 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Morning </td>
                    <td> 2/8 </td>
                    <td> 4/10 </td>
                    <td> 6/18 </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> 8/18 </td>
                    <td> 10/18 </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
         <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfDay </td>
                    <td> Evening </td>
                    <td> 0.25 </td>
                    <td> 0.4 </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Lunch </td>
                    <td> 0.5 </td>
                    <td> 0.2 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Morning </td>
                    <td> 0.25 </td>
                    <td> 0.4 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> </td>
                    <td> </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
         <td>
            <table>
                <tr>
                    <td colspan=3> Likelihood Table </td>
                </tr>
                <tr>
                    <td> trafficJam </td>
                    <td>  </td>
                    <td> No </td>
                    <td> Yes </td>
                    <td> Total </td>
                </tr>
                <tr>
                    <td> timeOfDay </td>
                    <td> Evening </td>
                    <td> -1.386294361 </td>
                    <td> -0.916290732 </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>  </td>
                    <td> Lunch </td>
                    <td> -0.69314718 </td>
                    <td> -1.60943792 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Morning </td>
                    <td> -1.386294362 </td>
                    <td> -0.91629073 </td>
                    <td> </td>
                </tr>
                 <tr>
                    <td>  </td>
                    <td> Total </td>
                    <td> </td>
                    <td> </td>
                    <td>  </td>
                </tr>
            </table>
        </td>
    </tr>    
</table>

--> <b>let's take TEST instance</b> <br>
weather : Clear &nbsp; timeOfWeek : Weekend &nbsp; timeOfDay: Evening &nbsp; trafficJam : ? <br>
weather: Snowy &nbsp; timeOfWeek: Workday &nbsp; timeOfDay: Morning  &nbsp; trafficJam : ? <br>

$ 
\begin{align}
P(y|X) = \frac{P(X|y) P(y)}{P(X)} 
\end{align}
$

--> <b>TestCase-1</b> <br>
weather : Clear &nbsp; timeOfWeek : Weekend &nbsp; timeOfDay: Evening &nbsp; trafficJam : ?

<b>let's calcualte $ P(y_{trafficJam}|X_{test}) $ for test sample 1 </b>
***

<b>Probability $ P(X|y):- $ </b><br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes) = \\
P(X_{weather} = Clear | y_{trafficJam} = Yes) * \\
P(X_{timeOfWeek} = Weekend | y_{trafficJam} = Yes) * \\
P(X_{timeOfDay} = Evening | y_{trafficJam} = Yes) * \\
\end{align}
$
<br>

$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes) = 2/10 * 2/10 * 4/10
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = Yes) = 10/18
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = Yes) = 10/18 * 2/10 * 2/10 * 4/10 = 0.00888889
\end{align}
$

***

$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No) = \\
P(X_{weather} = Clear | y_{trafficJam} = No) * \\
P(X_{timeOfWeek} = Weekend | y_{trafficJam} = No) * \\
P(X_{timeOfDay} = Evening | y_{trafficJam} = No) * \\
\end{align}
$
<br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No) = 4/8 * 7/8 * 2/8
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = No) = 8/18
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = No) = 8/18 * 4/8 * 7/8 * 2/8 = 0.0486111
\end{align}
$

***
$
\begin{align}
& evidence = 0.00888889 + 0.0486111 = 0.05749999 \\
& P(y_{trafficJam|X_{test}} = YES) = 0.00888889/0.05749999 = 0.154589418 \\
& P(y_{trafficJam|X_{test}} = No) = 0.0486111/0.05749999 = 0.84541058 \\
\end{align}
$
***
So, The anser is trafficJam = No

<b>Joint Likelihood $ P(X|y):- $ </b><br>
$ 
\begin{align}
log(P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes)) = \\
log(P(X_{weather} = Clear | y_{trafficJam} = Yes)) + \\
log(P(X_{timeOfWeek} = Weekend | y_{trafficJam} = Yes)) + \\
log(P(X_{timeOfDay} = Evening | y_{trafficJam} = Yes))  \\
\end{align}
$
<br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes) = -1.609437913 + -1.609437913 + -0.916290732 = -4.1351666
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = Yes) = -0.587796665
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = Yes) = -0.587796665 + -4.1351666 = -4.722963
\end{align}
$

***

The first part is $ P(X|y):- $ <br>
$ 
\begin{align}
log(P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No)) = \\
log(P(X_{weather} = Clear | y_{trafficJam} = No)) + \\
log(P(X_{timeOfWeek} = Weekend | y_{trafficJam} = No)) + \\
log(P(X_{timeOfDay} = Evening | y_{trafficJam} = No)) \\
\end{align}
$
<br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No) = -0.693147181 + -0.133531392 + -1.386294361 = -2.212973
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = No) = -0.81094021
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = No) = -0.81094021 + -2.212973 = -3.023913
\end{align}
$

***

So, The anser is trafficJam = No

--> <b>TestCase-2</b> <br>
weather: Snowy &nbsp; timeOfWeek: Workday &nbsp; timeOfDay: Morning  &nbsp; trafficJam : ? <br>

<b>let's calcualte $ P(y_{trafficJam}|X_{test}) $ for test sample 2 </b>

<b>Probability $ P(X|y):- $ </b><br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes) = \\
P(X_{weather} = Snowy | y_{trafficJam} = Yes) * \\
P(X_{timeOfWeek} = Workday | y_{trafficJam} = Yes) * \\
P(X_{timeOfDay} = Morning | y_{trafficJam} = Yes)  \\
\end{align}
$
<br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes) = 5/10 * 8/10 * 4/10
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = Yes) = 10/18
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = Yes) = 10/18 * 5/10 * 8/10 * 4/10 = 0.08888888
\end{align}
$

***

$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No) = \\
P(X_{weather} = Snowy | y_{trafficJam} = No) * \\
P(X_{timeOfWeek} = Workday | y_{trafficJam} = No) * \\
P(X_{timeOfDay} = Morning | y_{trafficJam} = No) * \\
\end{align}
$
<br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No) = 1/8 * 1/8 * 2/8
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = No) = 8/18
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = No) = 8/18 * 1/8 * 1/8 * 2/8 = 0.0017361
\end{align}
$

***
$
\begin{align}
& evidence = 0.08888888 + 0.0017361 = 0.09062498 \\
& P(y_{trafficJam|X_{test}} = YES) = 0.0888889/0.09062498 = 0.9808432 \\
& P(y_{trafficJam|X_{test}} = No) = 0.0017361/0.09062498 = 0.0191569 \\
\end{align}
$
***
So, The anser is trafficJam = Yes

<b>Joint Likelihood $ P(X|y):- $ </b><br>
$ 
\begin{align}
log(P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes)) = \\
log(P(X_{weather} = Snowy | y_{trafficJam} = Yes)) + \\
log(P(X_{timeOfWeek} = Workday | y_{trafficJam} = Yes)) + \\
log(P(X_{timeOfDay} = Morning | y_{trafficJam} = Yes))  \\
\end{align}
$
<br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = Yes) = -0.69314718 + -0.223143551 + -0.91629073 = -1.8325814
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = Yes) = -0.587796665
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = Yes) = -0.587796665 + -1.8325814 = -2.420378
\end{align}
$

***

$ 
\begin{align}
log(P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No)) = \\
log(P(X_{weather} = Snowy | y_{trafficJam} = No)) + \\
log(P(X_{timeOfWeek} = Workday | y_{trafficJam} = No)) + \\
log(P(X_{timeOfDay} = Morning | y_{trafficJam} = No)) \\
\end{align}
$
<br>
$ 
\begin{align}
P(X_{weather, timeOfWeek, timeOfDay}|y_{trafficJam} = No) = -2.079441541 + -2.0794415416 + -1.386294362 = -5.5451775
\end{align}
$
<br>
$ 
\begin{align}
P(y_{trafficJam} = No) = -0.81094021
\end{align}
$
<br>
So, $ P(X|y):- $ is [ ignoring denominator $P(X)$] <br>
$
\begin{align}
P(y_{trafficJam|X_{test}} = No) = -0.81094021 + -5.5451775 = -6.356117
\end{align}
$

***

So, The anser is trafficJam = Yes

## SciKit CategoricalNB <a class="anchor" id="sci_cnb"></a>

In [6]:
def preprocess(data_df):
    # Using ordinal encoder to convert the categories in the range from 0 to n-1
    
    wea_enc = OrdinalEncoder()
    weather_ = wea_enc.fit_transform(data_df["weather"].values.reshape(-1,1))

    timeOfWeek_enc = OrdinalEncoder()
    timeOfWeek_ = timeOfWeek_enc.fit_transform(data_df["timeOfWeek"].values.reshape(-1,1))
 
    timeOfDay_enc = OrdinalEncoder()
    timeOfDay_ = timeOfDay_enc.fit_transform(data_df["timeOfDay"].values.reshape(-1,1))
    
    # Stacking all the features
    X = np.column_stack((weather_,timeOfWeek_,timeOfDay_))
    
    # Changing the type to int
    X = X.astype(int)
    
    # Doing one hot encoding on the target data
    y = data_df['trafficJam']
    lb_enc = LabelEncoder()
    y_ = lb_enc.fit_transform(y)
    
    
    return X,y_, wea_enc, timeOfWeek_enc, timeOfDay_enc, lb_enc

In [7]:
X, y_, wea_enc, timeOfWeek_enc, timeOfDay_enc, lb_enc = preprocess(data_df)

# X_train=pd.DataFrame(X, columns=['weather', 'timeOfWeek', 'timeOfDay'])
X_train=X
y_train=y_

clf = CategoricalNB(alpha=1.0e-10)
clf.fit(X_train, y_train)

print(X_train.shape, y_train.shape)


print('Sklearn classes_\n',clf.classes_)
print('Sklearn class prior-probabilities\n',clf.class_log_prior_)

# print('Sklearn feature names \n',clf.feature_names_in_)
print('Sklearn feature log-probabilities')
for log_prob in clf.feature_log_prob_:
    print(log_prob)

(18, 3) (18,)
Sklearn classes_
 [0 1]
Sklearn class prior-probabilities
 [-0.81093022 -0.58778666]
Sklearn feature log-probabilities
[[-0.69314718 -0.98082925 -2.07944154]
 [-1.60943791 -1.2039728  -0.69314718]]
[[-0.13353139 -2.07944154]
 [-1.60943791 -0.22314355]]
[[-1.38629436 -0.69314718 -1.38629436]
 [-0.91629073 -1.60943791 -0.91629073]]

In [8]:
arr_test = [['Clear', 'Weekend', 'Evening']]
X_test_df=pd.DataFrame(arr_test, columns=['weather', 'timeOfWeek', 'timeOfDay'])

weather_ = wea_enc.transform(X_test_df["weather"].values.reshape(-1,1))

timeOfWeek_ = timeOfWeek_enc.transform(X_test_df["timeOfWeek"].values.reshape(-1,1))

timeOfDay_ = timeOfDay_enc.transform(X_test_df["timeOfDay"].values.reshape(-1,1))

# Stacking all the features
X_test = np.column_stack((weather_,timeOfWeek_,timeOfDay_))
# Changing the type to int
X_test = X_test.astype(int)
# X_test=pd.DataFrame(X_test, columns=['weather', 'timeOfWeek', 'timeOfDay'])
print(X_test)


y_pred = clf.predict(X_test)
print(y_pred)
print('Sklearn predict_proba\n', clf.predict_proba(X_test))
print('Sklearn predict_log_proba\n',clf.predict_log_proba(X_test))
print('Sklearn _joint_log_likelihood\n',clf._joint_log_likelihood(X_test))

[[0 0 0]]
[0]
Sklearn predict_proba
 [[0.84541063 0.15458937]]
Sklearn predict_log_proba
 [[-0.16793282 -1.86698289]]
Sklearn _joint_log_likelihood
 [[-3.02390315 -4.72295322]]

In [9]:
arr_test = [['Snowy', 'Workday', 'Morning']]
X_test_df=pd.DataFrame(arr_test, columns=['weather', 'timeOfWeek', 'timeOfDay'])

weather_ = wea_enc.transform(X_test_df["weather"].values.reshape(-1,1))

timeOfWeek_ = timeOfWeek_enc.transform(X_test_df["timeOfWeek"].values.reshape(-1,1))

timeOfDay_ = timeOfDay_enc.transform(X_test_df["timeOfDay"].values.reshape(-1,1))

# Stacking all the features
X_test = np.column_stack((weather_,timeOfWeek_,timeOfDay_))
# Changing the type to int
X_test = X_test.astype(int)
# X_test=pd.DataFrame(X_test, columns=['weather', 'timeOfWeek', 'timeOfDay'])
print(X_test)


y_pred = clf.predict(X_test)
print(y_pred)
print('Sklearn predict_proba\n', clf.predict_proba(X_test))
print('Sklearn predict_log_proba\n',clf.predict_log_proba(X_test))
print('Sklearn _joint_log_likelihood\n',clf._joint_log_likelihood(X_test))

[[2 1 2]]
[1]
Sklearn predict_proba
 [[0.01915709 0.98084291]]
Sklearn predict_log_proba
 [[-3.95508249 -0.01934296]]
Sklearn _joint_log_likelihood
 [[-6.35610766 -2.42036813]]

## Resources
1) https://python.plainenglish.io/naive-bayes-classification-algorithm-in-practice-40dd58d18df4
2) https://www.kaggle.com/code/gautigadu091/categorical-naive-bayes-from-scratch-in-python/notebook
3) https://towardsdatascience.com/naive-bayes-classifier-how-to-successfully-use-it-in-python-ecf76a995069
4) https://drive.google.com/drive/folders/1vldPQ6T88EVsjlRXvGtZUPPwZOffqrEb
5) https://remykarem.github.io/blog/naive-bayes.html
6) https://medium.com/@christopherfielding/na%C3%AFve-bayes-classification-for-discrete-and-continuous-variables-cb1103155488
7) https://datascience.stackexchange.com/questions/114651/sklearn-categorical-naive-bayes-vs-mathematical-theory-of-naive-bayes
8) https://towardsdatascience.com/why-how-to-use-the-naive-bayes-algorithms-in-a-regulated-industry-with-sklearn-python-code-dbd8304ab2cf